Week4
JokeBear777/nest-study-eventory pull request #13
Opened 2024-11-18 16:35 UTC by JokeBear777

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-20 09:27 UTC, worjs requested changes
코멘트 확인해주세요!

그리고 2단계로 나눠서 하신건 좋았지만 이 경우에는 migration이 필요한 케이스여서 두 db schema 변경 사이에 데이터를 migration하는 작업을 별도로 진행하셨어야 합니다.

수업때는 seed script를 만드는 법을 보여드렸었는데, 하셧으리라고 믿고(?) 넘어가겠습니다~

2024-11-20 09:27 UTC, worjs commented on package.json
> +    "yarn": "^1.22.22"
g랑 yarn은 뭔가요? ㅋㅋㅋ

2024-11-20 09:27 UTC, worjs commented on src/event/event.service.ts
> +      }
map써서 검사해야 한다는 부분 챙기신건 아주 좋지만
이렇게 하면 cityIds가 늘어날 수록 응답이 느려지게 됩니다.

코드 구조 자체가 getCityById를 보내고 받아서 체크하고 다음꺼 보내고 이런 식인데, 만약에 1000개쯤 있다고 하면 갔다왔다 해서 2000번의 네트워크 지연이 발생하게 되겠죠?

이 경우에는 in절 등을 활용해서 최대한 적은 횟수로 db 요청을 치는게 좋습니다.

2024-11-20 09:27 UTC, worjs commented on src/event/payload/create-event-payload.ts
> +  cityIds!: number[];
혹시 테스트 해보셨나요??

2024-11-20 09:27 UTC, worjs commented on src/event/type/event-data.ts
> +  }[];
굿!

2024-11-24 06:54 UTC, JokeBear777 commented
> 코멘트 확인해주세요!
> 
> 그리고 2단계로 나눠서 하신건 좋았지만 이 경우에는 migration이 필요한 케이스여서 두 db schema 변경 사이에 데이터를 migration하는 작업을 별도로 진행하셨어야 합니다.
> 
> 수업때는 seed script를 만드는 법을 보여드렸었는데, 하셧으리라고 믿고(?) 넘어가겠습니다~

migration을 하긴했는데 제대로 됐는지 확인할 수 있는 방법이 있을까요??

2024-11-24 07:18 UTC, worjs commented
음... 디비에 가서 Event에 있던 cityId 값이 EventCity로 잘 넘어갔는지 보면 될거같네용

2024-11-24 10:36 UTC, JokeBear777 commented
> 코멘트 확인해주세요!
> 
> 그리고 2단계로 나눠서 하신건 좋았지만 이 경우에는 migration이 필요한 케이스여서 두 db schema 변경 사이에 데이터를 migration하는 작업을 별도로 진행하셨어야 합니다.
> 
> 수업때는 seed script를 만드는 법을 보여드렸었는데, 하셧으리라고 믿고(?) 넘어가겠습니다~

2024-11-24 10:36 UTC, closed without merging