클럽 탈퇴하는 api
JokeBear777/nest-study-eventory pull request #35
Opened 2024-12-05 14:19 UTC by JokeBear777

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
유저가 클럽에서 탈퇴할때, 클럽 모임을 모두 탈퇴한 상태에서만 삭제 가능하게 구현했는데 이렇게 구현해도 될까요??

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-05 14:34 UTC, worjs requested changes

2024-12-05 14:34 UTC, worjs commented on src/club/club.service.ts
> +    }
넵 이부분도 사실 쉽지 않은게, 우리 로직에서는 이미 시작된 모임 탈퇴가 불가능해서, 사실상 클럽 모임을 한 개 참여한 모든 사용자가 탈퇴하지 못하게 됩니다.

아래와 같이 구현해주세요.
1. 탈퇴 시점에 시작되지 않은 모임에서는 탈퇴, 호스트라면 모임 삭제
2. 탈퇴 시점에 이미 시작된 모임이라면 그냥 유지.

2024-12-05 14:40 UTC, JokeBear777 commented on src/club/club.service.ts
> +    }
> 넵 이부분도 사실 쉽지 않은게, 우리 로직에서는 이미 시작된 모임 탈퇴가 불가능해서, 사실상 클럽 모임을 한 개 참여한 모든 사용자가 탈퇴하지 못하게 됩니다.
> 
> 아래와 같이 구현해주세요.
> 
> 1. 탈퇴 시점에 시작되지 않은 모임에서는 탈퇴, 호스트라면 모임 삭제
> 2. 탈퇴 시점에 이미 시작된 모임이라면 그냥 유지.

그냥 유지한다는 것이, 클럽 모임은 유지한 채로 클럽을 탈퇴하는 것인가요 아니면 클럽 모임도 유지하고 클럽 탈퇴도 못하게 되는 것인가요??

2024-12-05 15:21 UTC, worjs commented on src/club/club.service.ts
> +    }
삭제하지 않고 그냥 클럽만 나간다는 뜻입니다!

2024-12-06 03:17 UTC, worjs approved these changes

2024-12-06 03:17 UTC, worjs commented on src/club/club.repository.ts
> +            hostId: { not: userId },
`hostId: { not: userId }`
이 조건은 굳이? 필요 없을거같아요

어차피 아래에서 다 지우기도 하고

2024-12-06 04:07 UTC, merged