Week2
JokeBear777/nest-study-eventory pull request #4
Opened 2024-11-05 09:23 UTC by JokeBear777

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-05 15:34 UTC, worjs requested changes
전반적으로 좋습니다!

코멘트 받은 부분 한번씩 확인해주세요!

2024-11-05 15:34 UTC, worjs commented on src/event/event.controller.ts
> +  async createdEvent(@Body() payload: CreateEventPayload): Promise<EventDto> {
Post요청이 데이터 생성으로 쓰인 경우에는 201 Created가 더 적합합니다!

2024-11-05 15:34 UTC, worjs commented on src/event/event.controller.ts
> +  }
Query는 굳이 여기다가 `@Get(':/reviews?hostId&cityId&categoryId')`이렇게 정의 안해도 됩니다.
직접 Query 클래스 만들어다가 아래쪽에서 @Query 데코레이터를 통해 가져오고 있거든요.

2024-11-05 15:34 UTC, worjs commented on src/event/event.controller.ts
> +  }
그리고 reviews가 path에 들어가면 안될 것 같은데요 ㅎㅎㅎ

2024-11-05 15:34 UTC, worjs commented on src/event/event.controller.ts
> +  }
200을 리턴하기 때문에 Docs 데코레이터도 `@ApiOkResponse`가 맞습니다.

2024-11-05 15:34 UTC, worjs commented on src/event/event.service.ts
> +    }
이 3개의 조건문 중 하나는 없어도 될 것 같네요

2024-11-05 15:34 UTC, worjs commented on src/event/event.service.ts
> +  async createEvent(payload: CreateEventPayload): Promise<EventDto> {
createEvent를 하면 호스트는 가입한 상태가 되어야 한다는 요구사항이 만족되지 않았습니다!

2024-11-05 15:34 UTC, worjs commented on src/event/event.service.ts
> +    }
필요한 코드일까요?
events의 타입을 확인해보세요!

2024-11-05 15:34 UTC, worjs commented on src/event/payload/create-event-payload.ts
> +  endTime!: Date;
혹시 직접 api 요청 날려가면서 테스트 해보셨나요?
아마 이 부분때문에 400에러가 계속 발생할건데요, 요청 body(payload)가 객체로 매핑될 때 Date가 아니라 string으로 매핑되기 때문에, IsDate 데코레이터를 통과하지 못하기 때문입니다.

class-validator, class-transformer 라이브러리의 특징 때문에 발생한거라 다소 어려운데, 결론만 말하면

@Type(() => Date)를 추가해주어야 정상작동할겁니다!

2024-11-05 15:34 UTC, worjs commented on src/event/event.service.ts
> +  async createEvent(payload: CreateEventPayload): Promise<EventDto> {
maxPeople의 최소 인원에 대한 검증도 빠져있습니다!
400에러이니 payload 클래스에서 해결해 보시면 좋을듯.

https://github.com/typestack/class-validator
docs 참고하세요~

2024-11-05 15:34 UTC, worjs commented on src/event/event.service.ts
> +    }
굳이 둘 다 필요할까요?

2024-11-05 15:34 UTC, worjs commented on src/event/event.service.ts
> +    payload: UpdateEventJoinPayload,
아직 한 가지 검증이 더 필요합니다!

2024-11-05 15:34 UTC, worjs commented on src/event/event.service.ts
> +  ): Promise<void> {
마찬가지로 한 가지 검증이 더 필요합니다! 고민해보시고 힌트 필요하시면 알려주세요~

2024-11-05 15:35 UTC, worjs commented
꼭 서버 실행해서 api들 잘 동작하는지 직접 쳐보셔야 합니다~~~

2024-11-06 16:49 UTC, JokeBear777 reviewed
말씀하신대로 수정했는데
[Nest] 42228  - 2024. 11. 07. 오전 1:46:29     LOG [NestFactory] Starting Nest application...
[Nest] 42228  - 2024. 11. 07. 오전 1:46:29     LOG [InstanceLoader] CommonModule dependencies initialized +16ms
[Nest] 42228  - 2024. 11. 07. 오전 1:46:29   ERROR [ExceptionHandler] Nest can't resolve dependencies of the EventService (?). Please make sure that the argument Function at index [0] is available in the EventModule context.

Potential solutions:
- Is EventModule a valid NestJS module?
- If Function is a provider, is it part of the current EventModule?
- If Function is exported from a separate @Module, is that module imported within EventModule?
  @Module({
    imports: [ /* the Module containing Function */ ]
  })

Error: Nest can't resolve dependencies of the EventService (?). Please make sure that the argument Function at index [0] is available in the EventModule context.

Potential solutions:
- Is EventModule a valid NestJS module?
- If Function is a provider, is it part of the current EventModule?
- If Function is exported from a separate @Module, is that module imported within EventModule?
  @Module({
    imports: [ /* the Module containing Function */ ]
  })

    at Injector.lookupComponentInParentModules (C:\Users\kmw99\nest-study-eventory\node_modules\@nestjs\core\injector\injector.js:254:19)     
    at async Injector.resolveComponentInstance (C:\Users\kmw99\nest-study-eventory\node_modules\@nestjs\core\injector\injector.js:207:33)     
    at async resolveParam (C:\Users\kmw99\nest-study-eventory\node_modules\@nestjs\core\injector\injector.js:128:38)
    at async Promise.all (index 0)
    at async Injector.resolveConstructorParams (C:\Users\kmw99\nest-study-eventory\node_modules\@nestjs\core\injector\injector.js:143:27)     
    at async Injector.loadInstance (C:\Users\kmw99\nest-study-eventory\node_modules\@nestjs\core\injector\injector.js:70:13)
    at async Injector.loadProvider (C:\Users\kmw99\nest-study-eventory\node_modules\@nestjs\core\injector\injector.js:97:9)
    at async C:\Users\kmw99\nest-study-eventory\node_modules\@nestjs\core\injector\instance-loader.js:56:13
    at async Promise.all (index 3)
    at async InstanceLoader.createInstancesOfProviders (C:\Users\kmw99\nest-study-eventory\node_modules\@nestjs\core\injector\instance-loader.js:55:9)
    요런식으로 EventService의 의존성을 알수 없다고 뜨는데 왜그런지 알수있을까요??

2024-11-07 11:47 UTC, JokeBear777 commented
> 꼭 서버 실행해서 api들 잘 동작하는지 직접 쳐보셔야 합니다~~~

말씀하신대로 수정했는데
[Nest] 42228 - 2024. 11. 07. 오전 1:46:29 LOG [NestFactory] Starting Nest application...
[Nest] 42228 - 2024. 11. 07. 오전 1:46:29 LOG [InstanceLoader] CommonModule dependencies initialized +16ms
[Nest] 42228 - 2024. 11. 07. 오전 1:46:29 ERROR [ExceptionHandler] Nest can't resolve dependencies of the EventService (?). Please make sure that the argument Function at index [0] is available in the EventModule context.

Potential solutions:

Is EventModule a valid NestJS module?
If Function is a provider, is it part of the current EventModule?
If Function is exported from a separate @module, is that module imported within EventModule?
@module({
imports: [ /* the Module containing Function */ ]
})
Error: Nest can't resolve dependencies of the EventService (?). Please make sure that the argument Function at index [0] is available in the EventModule context.

Potential solutions:

Is EventModule a valid NestJS module?

If Function is a provider, is it part of the current EventModule?

If Function is exported from a separate @module, is that module imported within EventModule?
@module({
imports: [ /* the Module containing Function */ ]
})

at Injector.lookupComponentInParentModules (C:\Users\kmw99\nest-study-eventory\node_modules@nestjs\core\injector\injector.js:254:19)
at async Injector.resolveComponentInstance (C:\Users\kmw99\nest-study-eventory\node_modules@nestjs\core\injector\injector.js:207:33)
at async resolveParam (C:\Users\kmw99\nest-study-eventory\node_modules@nestjs\core\injector\injector.js:128:38)
at async Promise.all (index 0)
at async Injector.resolveConstructorParams (C:\Users\kmw99\nest-study-eventory\node_modules@nestjs\core\injector\injector.js:143:27)
at async Injector.loadInstance (C:\Users\kmw99\nest-study-eventory\node_modules@nestjs\core\injector\injector.js:70:13)
at async Injector.loadProvider (C:\Users\kmw99\nest-study-eventory\node_modules@nestjs\core\injector\injector.js:97:9)
at async C:\Users\kmw99\nest-study-eventory\node_modules@nestjs\core\injector\instance-loader.js:56:13
at async Promise.all (index 3)
at async InstanceLoader.createInstancesOfProviders (C:\Users\kmw99\nest-study-eventory\node_modules@nestjs\core\injector\instance-loader.js:55:9)
요런식으로 EventService의 의존성을 알수 없다고 뜨는데 왜그런지 알수있을까요??

2024-11-07 11:55 UTC, worjs commented
지금은 문제가 없어보이는데요 ... ????

2024-11-07 12:12 UTC, JokeBear777 commented
> 지금은 문제가 없어보이는데요 ... ????

넵 저도 다 확인해봤는데 딱히 문제가 없는데 같은 오류가 떠서 뭐가 문제인지 모르겠습니다 ㅠㅠ

2024-11-07 12:14 UTC, worjs commented
지금 이 리모트 브랜치(week2)랑 로컬의 week2랑 똑같은 상태인가요? 리모트로 올라와있는 브랜치는 문제 없거든요....

2024-11-07 12:26 UTC, JokeBear777 commented
> 지금 이 리모트 브랜치(week2)랑 로컬의 week2랑 똑같은 상태인가요? 리모트로 올라와있는 브랜치는 문제 없거든요....

넵 git pull origin week2 입력하고  해보았는데 똑같이 나옵니다

2024-11-07 12:27 UTC, worjs commented
그러면 혹시 푸쉬해보실 수 있나요,,,??? 이게 에러가 나는게 말이 안되는 상황이라...(?)

2024-11-07 12:28 UTC, worjs commented
브랜치 거기서 새로 만들어서 푸쉬하셔도 되고요

2024-11-07 12:34 UTC, JokeBear777 commented
> 브랜치 거기서 새로 만들어서 푸쉬하셔도 되고요

https://github.com/JokeBear777/nest-study-eventory/tree/Hello 
여기로 푸쉬햇씁니다!

2024-11-07 13:43 UTC, JokeBear777 commented
> 이거 왜 안되지... 진짜 아무리봐도 문제가 없어보여서 정신나가는줄.....알았습니다... 근데 말도안되는건 저였네요.. 일단 하나는 제가 워크플로우를 잘못 만든걸 지금 발견했구요....
> 
> 진짜 문제는 import type 문법이었습니다. 이게 import type을 사용하면 의존성 주입이 작동하지 않아서 생기는 문제입니다.
> 
> typescript는 우리가 코드짤때만 쓰고 실제로 실행할 때는 javascript 파일을 자동으로 생성해서 그걸 돌리는건 말씀드린 적이 있을것 같은데요, import type을 사용하면 타입만 임포트한다고 해서, javascript 파일로 변환되었을 때 import문 자체가 없어집니다.
> 
> 근데 nestjs는 의존성 주입이라고 해서 객체들을 생성하고 주입해주면서 연결하는 방식으로 서버를 켜는데, import문이 없으면 그걸 어디서 참조해야하는지 모르게되는거죠.
> 
> import type은 결국 나중에 배포할때(javascript 파일로 변환하여) 용량을 줄여주는 효과가 있는 것 같아요. 우린 그런거 신경쓸 필요 없으니까 모든 import type을 import로 그냥 쓰시는게 어떤가...... 예예...

말씀하신데로 type지우니까 해결되었습니다 예상치 못한 곳이 문제였네요 정말 감사합니다!

2024-11-07 14:18 UTC, merged