Feat/#10 change api
JokeBear777/nest-study-eventory pull request #41
Opened 2024-12-08 05:31 UTC by JokeBear777

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
기존 모임을 수정하여, 클럽 모임에 관한 것을 추가하였고,
리뷰의 조회부분도 삭제된 클럽 모임을 반영하여 수정하였습니다

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-08 11:08 UTC, worjs requested changes
헉 제가 코멘트 달아놓고 보내지를 않았었네요 ㅠㅠ 죄송합니다

2024-12-08 11:30 UTC, JokeBear777 commented on src/event/event.repository.ts
> +        }),
> 왜 갑자기 ...(query.eventId && 이런 포맷을 쓰게 되셨나요 하는 일은 기존 코드랑 똑같을 거예요

아하 저는 4개 다 받는것이 아니라, 클라리언트에서 4개중 원하는 조건 선택해서 0~4개 보내는줄 알았습니다

2024-12-08 11:30 UTC, JokeBear777 commented on src/event/event.repository.ts
> +        }),
> > 왜 갑자기 ...(query.eventId && 이런 포맷을 쓰게 되셨나요 하는 일은 기존 코드랑 똑같을 거예요
> 
> 아하 저는 조건 4개 다 받는것이 아니라, 클라리언트에서 4개중 원하는 조건 선택해서 0~4개 보내는줄 알았습니다

2024-12-08 11:36 UTC, worjs commented on src/event/event.repository.ts
> +        }),
기존 문법 자체가

> 클라리언트에서 4개중 원하는 조건 선택해서 0~4개 보내는줄 알았습니다
로 작동합니다ㅎㅎ

그 위치에 들어가는 값이 undefined면 조회 조건에서 빠지고, 값이 있으면 들어가는 식으로요!

2024-12-08 13:04 UTC, worjs commented on src/event/event.service.ts
> +    }
반복문 안에 쿼리 안됩니다!

2024-12-08 13:04 UTC, worjs commented on src/event/event.service.ts
> +      }
`!==`

2024-12-08 13:06 UTC, worjs commented on src/review/review.service.ts
> +
클럽원만 클럽 모임을 볼 수 있으니 리뷰도 마찬가지!

2024-12-08 13:06 UTC, worjs commented on src/review/review.service.ts
> +    const reviews = await this.reviewRepository.getReviews(query, user.id);
여기도 getEvents처럼 작업 필요합니다~

2024-12-08 14:16 UTC, JokeBear777 commented on src/review/review.service.ts
> +    const reviews = await this.reviewRepository.getReviews(query, user.id);
> 여기도 getEvents처럼 작업 필요합니다~

말씀하신것들 반영해서 다시 커밋하였습니다!

2024-12-08 14:35 UTC, worjs requested changes

2024-12-08 14:35 UTC, worjs commented on src/event/event.service.ts
> +    }
음 조회조건에 clubId로 아무것도 안넣더라도 내가 가입한 클럽의 모임은 조회되어야 하고, 가입하지 않은 클럼 모임은 필터링 되어야 합니다.

2024-12-08 14:35 UTC, worjs commented on src/event/event.repository.ts
> +    return new Set(joinedEvents.map((event) => event.eventId));
Set에서 감싸서 내보낼 필요가 있었나요?
eventJoin은 (userId, eventId)로 unique하기 때문에, 중복제거할 이유가 없거든요.

2024-12-08 14:35 UTC, worjs commented on src/event/event.repository.ts
> +    return new Set(joinedEvents.map((event) => event.eventId));
++메소드의 응답은 EventIds인데 이름이 부적절해보이네요!

2024-12-08 14:35 UTC, worjs commented on src/review/review.service.ts
> +    }
getEvents에서 드렸던 리뷰와 유사합니다!

2024-12-08 14:35 UTC, worjs commented on src/review/review.service.ts
> +    const events = await this.reviewRepository.getEventsByIds(eventIds);
이 경우는 Set에 넣어서 중복제거를 할 만합니다.
리뷰들을 조회했을 때 eventId가 겹칠 수 있죠.

2024-12-08 14:35 UTC, worjs commented on src/review/review.service.ts
> +      if (!event) return false;
event가 없을 가능성은 없습니다. 근데 find함수기 때문에 nullalbe하다고 타입이 잡힙니다.
어쩔 수 없이 예외처리할때는 false로 하는게 아니라 500에러를 던지는게 더 적절합니다.

2024-12-08 15:56 UTC, worjs requested changes
clubMember에서도 PENDING인 경우면 멤버로 쳐주면 안되는거니까, 그거 관련된 레포지토리 함수들 전부 수정해야 할 것 같습니다ㅠㅠ

2024-12-08 15:56 UTC, worjs commented on src/review/review.service.ts
> +
`!==`

2024-12-08 15:56 UTC, worjs commented on src/event/event.service.ts
> +    }
!==

2024-12-08 15:56 UTC, worjs commented on src/club/club.repository.ts
> +  }
status 체크를 했어야 했네요

2024-12-08 16:10 UTC, JokeBear777 commented on src/review/review.service.ts
> +
!==로 바꾼다면 undefined에 관한 처리도 추가해야 하나요?

2024-12-08 16:34 UTC, JokeBear777 commented on src/review/review.service.ts
> +
!= 대신에 !== 쓰는 이유가 뭔가요??

2024-12-08 16:45 UTC, JokeBear777 commented on src/review/review.service.ts
> +
만약에 !==로 고친다면 undefined도 넘어오게 되는게 그 부분은 따로 처리해야 하나요??

2024-12-08 16:56 UTC, JokeBear777 commented
> clubMember에서도 PENDING인 경우면 멤버로 쳐주면 안되는거니까, 그거 관련된 레포지토리 함수들 전부 수정해야 할 것 같습니다ㅠㅠ

수정해서 다시 커밋하였습니다.

2024-12-09 02:39 UTC, worjs approved these changes
그거만 고쳐서 마무리하시죠~

2024-12-09 02:39 UTC, worjs commented on src/club/club.repository.ts
> +  }
여기 아직 안되었네요ㅎㅎ

2024-12-09 05:49 UTC, merged