Week3
JokeBear777/nest-study-eventory pull request #5
Opened 2024-11-08 13:41 UTC by JokeBear777

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-09 02:40 UTC, worjs requested changes
굿 전체적으로 좋습니다!

코멘트 확인해주세요~

2024-11-09 02:40 UTC, worjs commented on src/event/event.service.ts
> +      throw new NotFoundException('지역이 존재하지 않습니다.');
getCategoryById라는 함수가 가져오는 값을 변수로 표현하면 isCategoryExist라고 하는 것이 적절할까요?

2024-11-09 02:40 UTC, worjs commented on src/event/event.service.ts
> +    }
두 조건은 중복되는 조건이 아닐까요?

2024-11-09 02:40 UTC, worjs commented on src/event/event.service.ts
> +  ): Promise<EventDto> {
거의 좋습니다! 아직 한가지? 정도 요구사항이 반영이 안된 게 있네요.

2024-11-09 02:40 UTC, worjs commented on src/event/event.service.ts
> +  }
이미 누군가 모임에 가입한 상태에서 한번 테스트해보시겠어요?

2024-11-10 09:48 UTC, JokeBear777 commented on src/event/event.service.ts
> +  }
말씀하신거 반영해서 수정했습니다 감사합니다

2024-11-10 09:50 UTC, JokeBear777 commented
> 굿 전체적으로 좋습니다!
> 
> 코멘트 확인해주세요~

말씀하신거 반영해서 수정했습니다 감사합니다!

2024-11-10 10:16 UTC, worjs commented on src/event/event.service.ts
> +    }
음 그러니까 제가 보기에는 payload.endTime을 확인할 필요가 없지 않냐는 의미였습니다.
어차피 startTime이 now보다 빠르기만 해도 에러를 뱉을건데, endTime은 startTime보다 늦어야 한다고 아래에서 확인하고 있으니까요

2024-11-10 10:16 UTC, worjs approved these changes
LGTM!
문제없어보입니다 고생하셨어요!

2024-11-10 15:00 UTC, merged